CREATE DATABASE IF NOT EXISTS sword;

USE sword;

CREATE TABLE IF NOT EXISTS users (
	LOGIN VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    STATUS ENUM('admin', 'user') DEFAULT 'user' NOT NULL,
    ID INT AUTO_INCREMENT PRIMARY KEY
);