USE ucode_web;

CREATE TABLE IF NOT EXISTS heroes (
	NAME VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CLASS_ROLE ENUM('tankman', 'healer', 'dps') NOT NULL,
    RACE VARCHAR(255) NOT NULL DEFAULT 'human',
    ID INT AUTO_INCREMENT PRIMARY KEY
);